apiVersion: apps/v1
kind: Deployment
metadata:
  name: hasher-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hasher
      app: dockercoins
  template:
    metadata:
      labels:
        app: hasher
        app: dockercoins
    spec:
      containers:
        -
          args:
            - hasher.rb
          command:
            - ruby
          image: celsohernando/hasher:latest
          name: hasher-container
          ports: 
            - 
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            -
              mountPath: /hasher/hasher.rb
              name: hasher-volume
              readOnly: true
              subPath: hasher.rb
          workingDir: /hasher/   
      volumes:
        -
          secret:
            defaultMode: 0400
            items:
              -
                key: hasher.rb
                mode: 0400
                path: hasher.rb
            secretName: hasher-secret
          name: hasher-volume
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      app: dockercoins
  template:
    metadata:
      labels:
        app: redis
        app: dockercoins
    spec:
      containers:
        -
          args:
            - redis-server
          command:
            - docker-entrypoint.sh
          image: celsohernando/redis:latest
          name: redis-container
          ports: 
            - 
              containerPort: 6379
              protocol: TCP
          volumeMounts:
            -
              mountPath: /data/
              name: redis-volume
              readOnly: false
          workingDir: /data/   
      volumes:
        -
          emptyDir:
            medium: Memory
            sizeLimit: 100Mi
          name: redis-volume
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: rng-ds
spec:
  selector:
    matchLabels:
      app: rng
      app: dockercoins
  template:
    metadata:
      labels:
        app: rng
        app: dockercoins
    spec:
      containers:
        -
          args:
            - rng.py
          command:
            - python
          image: celsohernando/rng:latest
          name: rng-container
          ports: 
            - 
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            -
              mountPath: /rng/rng.py
              name: rng-volume
              readOnly: true
              subPath: rng.py
          workingDir: /rng/   
      volumes:
        -
          secret:
            defaultMode: 0400
            items:
              -
                key: rng.py
                mode: 0400
                path: rng.py
            secretName: rng-secret
          name: rng-volume
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webui-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webui
      app: dockercoins
  template:
    metadata:
      labels:
        app: webui
        app: dockercoins
    spec:
      containers:
        -
          args:
            - webui.js
          command:
            - node
          image: celsohernando/webui:latest
          name: webui-container
          ports: 
            - 
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            -
              mountPath: /dockercoins/
              name: webui-volume
              readOnly: true
          workingDir: /dockercoins/webui/   
      initContainers:
        -
          args:
            - clone
            - https://github.com/celsohernando/dockercoins
            - --branch
            - 2021-12-ibm
            - --single-branch
            - /dockercoins/
          image: celsohernando/git:latest
          name: webui-init-container
          volumeMounts:
            -
              mountPath: /dockercoins/
              name: webui-volume
              readOnly: false
          workingDir: /dockercoins/   
      volumes:
        -
          persistentVolumeClaim:
            claimName: webui-pvc
            readOnly: false
          name: webui-volume
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker
      app: dockercoins
  template:
    metadata:
      labels:
        app: worker
        app: dockercoins
    spec:
      containers:
        -
          args:
            - worker.py
          command:
            - python
          image: celsohernando/worker:latest
          name: worker-container
          volumeMounts:
            -
              mountPath: /worker/worker.py
              name: worker-volume
              readOnly: true
              subPath: worker.py
          workingDir: /worker/   
      volumes:
        -
          secret:
            defaultMode: 0400
            items:
              -
                key: worker.py
                mode: 0400
                path: worker.py
            secretName: worker-secret
          name: worker-volume
---

